### ISSUE TITLE
Build problems with loom

### ISSUE THREAD

**Issue by ssinghal53** [HewlettPackard/loom#5]
I downloaded loom (windows 10, Java 1.8_131, Eclipse Neon). Git downloaded everything fine on my home machine, and Eclipse imported all 18 projects using Maven (built into Eclipse). Everything built, except loom-server. A maven build test failed with the attached log.

Since I tend to stay within the Eclipse IDE for everything, and am relying on it (no command lines), maybe there is some config setting I'm missing. Also, since I have 18 separate projects in my workspace, is there a single place where I do "mvn clean install" or do I need to do it under each project?

Maven fails at work (all the pom.xml files show errors) because maven is failing to locate the correct proxy, so am running everything on my home machine. 

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building loom-server 3.11-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.hp.hpl.loom:loom-common:jar:3.11-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.hp.hpl.loom:loom-adapter:jar:3.11-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.hp.hpl.loom:loom-client:jar:3.11-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.hp.hpl.loom:os-adapter:jar:3.11-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.hp.hpl.loom:file-adapter:jar:3.11-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.hp.hpl.loom:stitcher:jar:3.11-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.836 s
[INFO] Finished at: 2017-07-18T20:21:52-07:00
[INFO] Final Memory: 8M/91M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project loom-server: Could not resolve dependencies for project com.hp.hpl.loom:loom-server:war:3.11-SNAPSHOT: The following artifacts could not be resolved: com.hp.hpl.loom:loom-common:jar:3.11-SNAPSHOT, com.hp.hpl.loom:loom-adapter:jar:3.11-SNAPSHOT, com.hp.hpl.loom:loom-client:jar:3.11-SNAPSHOT, com.hp.hpl.loom:os-adapter:jar:3.11-SNAPSHOT, com.hp.hpl.loom:file-adapter:jar:3.11-SNAPSHOT, com.hp.hpl.loom:stitcher:jar:3.11-SNAPSHOT: Could not find artifact com.hp.hpl.loom:loom-common:jar:3.11-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by rychardeh** [comment]
I build from the command line.  Which project did you choose to start your maven build from?  `loom-parent` (which corresponds to the top level folder) will build everything including the front-end.  The `loom` project (which corresponds to ~/loom) will build only the back-end components.  Subprojects like `loom-server` (~/loom/loom-server) will only build the server.  However unless the dependencies have been built previously, e.g. `loom-common`, it will fail.  I would choose to build from `loom` when developing the back-end and all should be fine.

I have just done this from Eclipse (albeit with an already populate local maven repository) and it works fine.

**Comment by ssinghal53** [comment]
My eclipse environment is set to auto-build, so I'm not sure in which order eclipse tried to resolve the dependencies. Let me turn auto-build off, and explicitly do a build from loom-parent tonight. Will also get a new clean copy of loom to do it.

**Comment by ssinghal53** [comment]
Attached is the new build log. I did "maven clean" then "maven install" in the top level loom directory. Can also install maven directly and try from the command line.
[build-log.txt](https://github.com/HewlettPackard/loom/files/1161094/build-log.txt)

**Comment by rychardeh** [comment]
Checkstyle is failing with a CR/LF issue.  I build under Window with no issues and I've done a build on a new Ubuntu machine with no issues either.  So the problem is in your environment.  I think you maybe don't have git set up correctly to handle cross platform dev.  See the following article: https://help.github.com/articles/dealing-with-line-endings/

Check that core.autocrlf is true. If you have to set it you will need to wipe your local working copy and pull again.

**Comment by ssinghal53** [comment]
The problem was with eclipse not picking up the correct git configuration (core.autocrlf was true in git, but not in Eclipse). Now using git on the command line as well. I'm doing the clean install (after getting a new loom repository, and deleting everything in .m2 directory. Gets a lot further this time, but reports an error on weaver-parent. Tail of the log attached.
[build-log2.txt](https://github.com/HewlettPackard/loom/files/1162804/build-log2.txt)
Thanks for the patience. Any suggestions?

**Comment by rychardeh** [comment]
You need to node v0.12 as mentioned in the front-end README https://github.com/HewlettPackard/loom/blob/master/front-end/README.md

I would strongly recommend using `nvm` for installing it since tm-ed uses a different version of node and juggling them is painful otherwise.  On Windows I use https://github.com/coreybutler/nvm-windows

Once installed you basically do

> nvm install 0.12
> nvm use 0.12

And then your environment should be ready to build the front-end.

**Comment by ssinghal53** [comment]
Ok. That works. Here is the final log. I call it done.
there were _lots_ of warnings that the old version of node.js being used has security holes in it, so I'd recommend upgrading to a newer version if possible
